import { makeStaticStyles, makeStyles, shorthands, tokens } from "@fluentui/react-components";

export const useGlobalStyles = makeStaticStyles({
  "html, body, #root": {
    minHeight: "100%",
  },
  body: {
    margin: 0,
    overflowX: "hidden",
  },
  "*, *::before, *::after": {
    boxSizing: "border-box",
  },
});

export const useAppStyles = makeStyles({
  provider: {
    minHeight: "100vh",
    backgroundColor: tokens.colorNeutralBackground2,
    color: tokens.colorNeutralForeground1,
  },
  skipLink: {
    position: "fixed",
    top: 0,
    left: tokens.spacingHorizontalM,
    zIndex: 10,
    padding: `${tokens.spacingVerticalS} ${tokens.spacingHorizontalM}`,
    color: tokens.colorNeutralForegroundOnBrand,
    backgroundColor: tokens.colorBrandBackground,
    borderRadius: tokens.borderRadiusMedium,
    transform: "translateY(-100%)",
    transitionProperty: "transform",
    transitionDuration: tokens.durationNormal,
    ":focus": {
      transform: "translateY(0)",
    },
  },
  shell: {
    display: "flex",
    flexWrap: "wrap",
    minHeight: "100vh",
  },
  sidebar: {
    flexGrow: 0,
    flexShrink: 0,
    flexBasis: `calc(${tokens.spacingHorizontalXXXL} * 8)`,
    minWidth: `min(100%, calc(${tokens.spacingHorizontalXXXL} * 8))`,
    display: "flex",
    flexDirection: "column",
    gap: tokens.spacingVerticalL,
    padding: tokens.spacingHorizontalL,
    backgroundColor: tokens.colorNeutralBackground3,
    borderRightColor: tokens.colorNeutralStroke2,
    borderRightStyle: "solid",
    borderRightWidth: tokens.strokeWidthThin,
  },
  brand: {
    display: "flex",
    flexDirection: "column",
    gap: tokens.spacingVerticalXXS,
  },
  nav: {
    display: "flex",
    flexDirection: "column",
    gap: tokens.spacingVerticalXS,
  },
  navLink: {
    display: "block",
    padding: `${tokens.spacingVerticalS} ${tokens.spacingHorizontalM}`,
    color: tokens.colorNeutralForeground2,
    textDecorationLine: "none",
    borderRadius: tokens.borderRadiusMedium,
    borderLeftColor: "transparent",
    borderLeftStyle: "solid",
    borderLeftWidth: tokens.strokeWidthThick,
    ":hover": {
      color: tokens.colorNeutralForeground1,
      backgroundColor: tokens.colorNeutralBackground1Hover,
    },
  },
  navLinkActive: {
    color: tokens.colorNeutralForeground1,
    backgroundColor: tokens.colorBrandBackground2,
    borderLeftColor: tokens.colorBrandStroke1,
    fontWeight: tokens.fontWeightSemibold,
  },
  sidebarFoot: {
    marginTop: "auto",
    overflowWrap: "anywhere",
    color: tokens.colorNeutralForeground3,
  },
  main: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: `calc(${tokens.spacingHorizontalXXXL} * 22)`,
    minWidth: 0,
    padding: tokens.spacingHorizontalXXL,
    outlineStyle: "none",
  },
  topbar: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: tokens.spacingHorizontalL,
    marginBottom: tokens.spacingVerticalXXL,
  },
  titleBlock: {
    display: "flex",
    flexDirection: "column",
    gap: tokens.spacingVerticalXS,
    minWidth: 0,
  },
  heading: {
    margin: 0,
    outlineStyle: "none",
  },
  subtitle: {
    color: tokens.colorNeutralForeground3,
  },
  topActions: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "end",
    gap: tokens.spacingHorizontalM,
  },
  languageGroup: {
    display: "flex",
    gap: tokens.spacingHorizontalXS,
  },
  page: {
    display: "flex",
    flexDirection: "column",
    gap: tokens.spacingVerticalL,
  },
  pageToolbar: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "end",
    gap: tokens.spacingHorizontalS,
  },
  grid: {
    display: "grid",
    gridTemplateColumns: `repeat(auto-fit, minmax(min(100%, calc(${tokens.spacingHorizontalXXXL} * 9)), 1fr))`,
    gap: tokens.spacingHorizontalL,
  },
  card: {
    minWidth: 0,
  },
  cardHeader: {
    paddingBottom: tokens.spacingVerticalS,
  },
  cardBody: {
    display: "flex",
    flexDirection: "column",
    gap: tokens.spacingVerticalM,
    minWidth: 0,
  },
  metricGrid: {
    display: "grid",
    gridTemplateColumns: `repeat(auto-fit, minmax(min(100%, calc(${tokens.spacingHorizontalXXXL} * 5)), 1fr))`,
    gap: tokens.spacingHorizontalM,
  },
  metric: {
    display: "flex",
    flexDirection: "column",
    gap: tokens.spacingVerticalXS,
    padding: tokens.spacingHorizontalM,
    backgroundColor: tokens.colorNeutralBackground3,
    borderRadius: tokens.borderRadiusMedium,
    ...shorthands.border(tokens.strokeWidthThin, "solid", tokens.colorNeutralStroke2),
  },
  metricValue: {
    fontSize: tokens.fontSizeBase600,
    lineHeight: tokens.lineHeightBase600,
    fontWeight: tokens.fontWeightSemibold,
  },
  stack: {
    display: "flex",
    flexDirection: "column",
    gap: tokens.spacingVerticalM,
  },
  inline: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: tokens.spacingHorizontalS,
  },
  spread: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "space-between",
    gap: tokens.spacingHorizontalM,
  },
  tableRegion: {
    maxWidth: "100%",
    overflowX: "auto",
    ...shorthands.border(tokens.strokeWidthThin, "solid", tokens.colorNeutralStroke2),
    borderRadius: tokens.borderRadiusMedium,
    ":focus-visible": {
      outlineColor: tokens.colorStrokeFocus2,
      outlineStyle: "solid",
      outlineWidth: tokens.strokeWidthThick,
      outlineOffset: tokens.strokeWidthThin,
    },
  },
  table: {
    minWidth: `calc(${tokens.spacingHorizontalXXXL} * 21)`,
  },
  compactTable: {
    minWidth: `calc(${tokens.spacingHorizontalXXXL} * 12)`,
  },
  timelineRecord: {
    display: "flex",
    flexDirection: "column",
    gap: tokens.spacingVerticalXS,
  },
  muted: {
    color: tokens.colorNeutralForeground3,
  },
  code: {
    fontFamily: tokens.fontFamilyMonospace,
    fontSize: tokens.fontSizeBase200,
    overflowWrap: "anywhere",
  },
  codeBlock: {
    margin: 0,
    padding: tokens.spacingHorizontalM,
    overflowX: "auto",
    whiteSpace: "pre-wrap",
    overflowWrap: "anywhere",
    color: tokens.colorNeutralForeground1,
    backgroundColor: tokens.colorNeutralBackground3,
    fontFamily: tokens.fontFamilyMonospace,
    fontSize: tokens.fontSizeBase200,
    borderRadius: tokens.borderRadiusMedium,
    ...shorthands.border(tokens.strokeWidthThin, "solid", tokens.colorNeutralStroke2),
  },
  empty: {
    padding: tokens.spacingHorizontalXXL,
    textAlign: "center",
    color: tokens.colorNeutralForeground3,
  },
  fieldGrid: {
    display: "flex",
    flexWrap: "wrap",
    gap: tokens.spacingHorizontalL,
    alignItems: "start",
  },
  fieldIdentity: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: `calc(${tokens.spacingHorizontalXXXL} * 7)`,
    display: "flex",
    flexDirection: "column",
    gap: tokens.spacingVerticalXXS,
    minWidth: 0,
  },
  fieldControl: {
    flexGrow: 2,
    flexShrink: 1,
    flexBasis: `calc(${tokens.spacingHorizontalXXXL} * 12)`,
    display: "flex",
    flexDirection: "column",
    gap: tokens.spacingVerticalXS,
    minWidth: 0,
  },
  inputLine: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: tokens.spacingHorizontalS,
    minWidth: 0,
  },
  grow: {
    flexGrow: 1,
    flexBasis: `calc(${tokens.spacingHorizontalXXXL} * 7)`,
    minWidth: 0,
  },
  resolved: {
    color: tokens.colorNeutralForeground3,
    overflowWrap: "anywhere",
  },
  listItem: {
    display: "flex",
    flexDirection: "column",
    gap: tokens.spacingVerticalXS,
    padding: tokens.spacingHorizontalM,
    backgroundColor: tokens.colorNeutralBackground3,
    borderRadius: tokens.borderRadiusMedium,
    ...shorthands.border(tokens.strokeWidthThin, "solid", tokens.colorNeutralStroke2),
  },
  operationSummary: {
    margin: 0,
    color: tokens.colorNeutralForeground2,
  },
});
